### PR TITLE
add keypairs files

### PR DESCRIPTION
**Pull request by tawalton**

### CODE REVIEW

**Comment by ghost** [comment]
This is ready for review besides the patch failure on codecov

**Comment by ghost** [comment]
@tawalton this pr is ready to go to mimic core I think, let me know if you think this is good and Ill merge it into your forks master as well.

Here is it working on reach:
image

**Comment by tawalton** [comment]
@gabecase can you update this PR with the changes in rackerlabs/mimic so we can get it merged in here

**Comment by ghost** [comment]
Will do! I know I added some test etc... so I will update this PR with those changes as well.

**Pull request merged**
